site_name: 'python-app-v5'
site_description: 'Main documentation for the python-app-v5'
repo_url: https://github.com/ricardoandre97/python-app-v5
edit_uri: edit/main/docs

plugins:
  - techdocs-core

# For sidebar navigation on https://backstage.io/, see `microsite/sidebars.json`
nav:
  - Overview:
      - Getting started: 'docs/index.md'