replicaCount: 2

image:
  repository: rafaelvieira96/python-app-v5
  pullPolicy: IfNotPresent
  # tag: python-app-v5-dev-latest
  tag: latest

resources:
  requests:
    cpu: 60m
    memory: 60M